/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class addbook extends javax.swing.JInternalFrame {

    /**
     * Creates new form addbook
     */Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public addbook() {
        initComponents();
        con=dbconnect.connect();
        autoid();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbbid = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbbcode = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpublisher = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btdelete = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        caldate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        txtname = new javax.swing.JTextField();
        txtbcode = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        cmbcategory = new javax.swing.JComboBox();
        cmbbooktype = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbbid.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        lbbid.setText("Book ID");
        jPanel1.add(lbbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lbname.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        lbname.setText("Name");
        jPanel1.add(lbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        lbbcode.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        lbbcode.setText("B code");
        jPanel1.add(lbbcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setText("Category");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtpublisher.setColumns(20);
        txtpublisher.setRows(5);
        jScrollPane1.setViewportView(txtpublisher);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 150, 130));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel10.setText("Book type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        btdelete.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 160, 40));

        btadd.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        jPanel1.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 160, 40));

        btupdate.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 160, 40));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, 220));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setText("Publisher");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        jPanel1.add(caldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setText("Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        txtbid.setEditable(false);
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, -1));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 397, 930, 160));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, -1));

        txtbcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbcodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtbcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 150, -1));

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select category", "Language", "Technology", "History", "Other" }));
        jPanel1.add(cmbcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, -1));

        cmbbooktype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type", "Borrow", "Read only" }));
        cmbbooktype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbooktypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbbooktype, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 150, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 930, 270));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 950, 460));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel5.setText("Books");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 100));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbooktypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbooktypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbooktypeActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
        String bid= txtbid.getText();
        String bname= txtname.getText();
        String bcode= txtbcode.getText();
        String date=((JTextField)caldate.getDateEditor().getUiComponent()).getText();
        String category =cmbcategory.getSelectedItem().toString();
                String publisher= txtpublisher.getText();
        String price= txtprice.getText();
        //String contact= txtcno.getText();
        String booktype= cmbbooktype.getSelectedItem().toString();
        
      
        try
        {
            String sql="UPDATE `addbook` SET `bname`='"+bname+"',`bcode`='"+bcode+"',`date`='"+date+"',`category`='"+category+"',`booktype`='"+booktype+"',`publisher`='"+publisher+"',`price`='"+price+"'  WHERE `bid`='"+txtbid.getText()+"' ";
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"update successful");
            table();
            clear();
        }catch(Exception e)
        {
                        JOptionPane.showMessageDialog(rootPane,e);

        }
    
    }//GEN-LAST:event_btupdateActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        
             try{
            String sql="DELETE FROM `addbook` WHERE bid='"+txtbid.getText()+"'";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.execute();                          
            JOptionPane.showMessageDialog(rootPane,"successfully deleted ");
            
            table();            
     //  clear();     
            
        }catch(Exception e)
        {
                        JOptionPane.showMessageDialog(rootPane,e);

        }
             clear();
    
    }//GEN-LAST:event_btdeleteActionPerformed

    private void txtbcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbcodeActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        
         String bid= txtbid.getText();
        String bname= txtname.getText();
        String bcode= txtbcode.getText();
        String date=((JTextField)caldate.getDateEditor().getUiComponent()).getText();
        String category =cmbcategory.getSelectedItem().toString();
                String publisher= txtpublisher.getText();
        String price= txtprice.getText();
        //String contact= txtcno.getText();
        String booktype= cmbbooktype.getSelectedItem().toString();
        
        
        try
        {
            
            String sql="INSERT INTO `addbook`(`bid`, `bname`, `bcode`, `date`, `category`, `booktype`, `publisher`, `price`,`mark`) VALUES ('"+bid+"','"+bname+"','"+bcode+"','"+date+"','"+category+"','"+booktype+"','"+publisher+"','"+price+"','0')";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.execute();                          
                         JOptionPane.showMessageDialog(rootPane,"successful entered");
          
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
            
         clear();
        
autoid();
table();
        

    
    }//GEN-LAST:event_btaddActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        
        
          DefaultTableModel tmodel=(DefaultTableModel)tbldata.getModel();
        int selectrowindex =tbldata.getSelectedRow();
        
        
        
        txtbid.setText(tmodel.getValueAt(selectrowindex,0).toString());
                txtname.setText(tmodel.getValueAt(selectrowindex,1).toString());
        txtbcode.setText(tmodel.getValueAt(selectrowindex,2).toString());
        ((JTextField)caldate.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex,3).toString());

        
        
        
        
        
        cmbcategory.setSelectedItem(tmodel.getValueAt(selectrowindex,4).toString());
         //txtaddress.setText(tmodel.getValueAt(selectrowindex,5).toString());
          txtpublisher.setText(tmodel.getValueAt(selectrowindex,6).toString());
           txtprice.setText(tmodel.getValueAt(selectrowindex,7).toString());
                   cmbbooktype.setSelectedItem(tmodel.getValueAt(selectrowindex,5).toString());
                   
                   
                   
                   
                   

           
        
        
    
    }//GEN-LAST:event_tbldataMouseClicked

    private void table()
    {
        try{
            
            String sql2="SELECT `bid`, `bname`, `bcode`, `date`, `category`, `booktype`, `publisher`, `price` FROM `addbook` ";
            pst= con.prepareStatement(sql2);
            rs=pst.executeQuery();
            tbldata.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    private void autoid(){
        try
        {
            
            String sql1="SELECT `bid` FROM `addbook` ORDER BY bid DESC LIMIT 1";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                
                String rno= rs.getString("bid");
                int co= rno.length();
                String txt=rno.substring(0,2);
                String num=rno.substring(2,co);
                int n=Integer.parseInt(num);
                ++n;
                String sum=Integer.toString(n);
                String ftxt=txt+sum;
                txtbid.setText(ftxt);
        }else
            {
                txtbid.setText("BI1000");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
     private void clear()
    {
// String bid= txtbid.getText();
        txtname.setText("");
        txtbcode.setText("");
        ((JTextField)caldate.getDateEditor().getUiComponent()).setText("");
        cmbcategory.setSelectedIndex(0);
                txtpublisher.setText("");
        txtprice.setText("");
        //txtcno.setText("");
        cmbbooktype.setSelectedIndex(0);
        
        
        
        
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btupdate;
    private com.toedter.calendar.JDateChooser caldate;
    private javax.swing.JComboBox cmbbooktype;
    private javax.swing.JComboBox cmbcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbbcode;
    private javax.swing.JLabel lbbid;
    private javax.swing.JLabel lbname;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField txtbcode;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextArea txtpublisher;
    // End of variables declaration//GEN-END:variables
}
