/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class Addmember extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Addmember() {
        initComponents();
        con=dbconnect.connect();
        autoid();
        table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtemail = new javax.swing.JTextField();
        txtcno = new javax.swing.JTextField();
        cmbmtype = new javax.swing.JComboBox();
        cmbgender = new javax.swing.JComboBox();
        calbday = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        btadd = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 30)); // NOI18N
        jLabel15.setText("Member");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 310, 60));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 970, 100));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel5.setText("Member ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel7.setText("NIC");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel8.setText("Birthday");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setText("Contact No.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel13.setText("Member type");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));
        jPanel1.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, -1));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 70));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 150, -1));
        jPanel1.add(txtcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 150, -1));

        cmbmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Other" }));
        jPanel1.add(cmbmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 140, -1));

        cmbgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select gender", "Male", "female", "Other", " " }));
        jPanel1.add(cmbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, -1));
        jPanel1.add(calbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, -1));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 347, 960, 240));

        btadd.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        jPanel1.add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 153, 200, 30));

        btupdate.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 213, 200, 30));

        btdelete.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 273, 210, 30));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 290, 180));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 960, 230));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 110, 960, 480));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 600));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        try{
            String sql="DELETE FROM `addmember` WHERE mid='"+txtid.getText()+"'";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.execute();                          
            JOptionPane.showMessageDialog(rootPane,"successfully deleted ");
            
            table();            
            
            
        }catch(Exception e)
        {
                        JOptionPane.showMessageDialog(rootPane,e);

        }
    }//GEN-LAST:event_btdeleteActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        
        String mid= txtid.getText();
        String name= txtname.getText();
        String nic= txtnic.getText();
        String birthday=((JTextField)calbday.getDateEditor().getUiComponent()).getText();
        String gender =cmbgender.getSelectedItem().toString();
                String address= txtaddress.getText();
        String email= txtemail.getText();
        String contact= txtcno.getText();
        String type= cmbmtype.getSelectedItem().toString();
        
        
        try
        {
            
            String sql="INSERT INTO `addmember`(`mid`, `name`, `nic`, `birthday`, `gender`, `address`, `email`, `contact`, `type`) VALUES('"+mid+"','"+name+"','"+nic+"','"+birthday+"','"+gender+"','"+address+"','"+email+"','"+contact+"','"+type+"')";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.execute();                          
                         JOptionPane.showMessageDialog(rootPane,"successful entered");
          
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
            
         clear();
        
autoid();
table();
        

    }//GEN-LAST:event_btaddActionPerformed
    
    private void table()
    {
        try{
            
            String sql2="SELECT `mid`, `name`, `nic`, `birthday`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember` ";
            pst= con.prepareStatement(sql2);
            rs=pst.executeQuery();
            tbldata.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    private void autoid(){
        try
        {
            
            String sql1="SELECT `mid` FROM `addmember` ORDER BY mid DESC LIMIT 1";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                
                String rno= rs.getString("mid");
                int co= rno.length();
                String txt=rno.substring(0,2);
                String num=rno.substring(2,co);
                int n=Integer.parseInt(num);
                ++n;
                String sum=Integer.toString(n);
                String ftxt=txt+sum;
                txtid.setText(ftxt);
        }else
            {
                txtid.setText("MI1000");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    private void clear()
    {
 String mid= txtid.getText();
        txtname.setText("");
        txtnic.setText("");
        ((JTextField)calbday.getDateEditor().getUiComponent()).setText("");
        cmbgender.setSelectedIndex(0);
                txtaddress.setText("");
        txtemail.setText("");
        txtcno.setText("");
        cmbmtype.setSelectedIndex(0);
        
        
        
        
        
        
    }
    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
          String mid= txtid.getText();
        String name= txtname.getText();
        String nic= txtnic.getText();
        String birthday=((JTextField)calbday.getDateEditor().getUiComponent()).getText();
        String gender =cmbgender.getSelectedItem().toString();
                String address= txtaddress.getText();
        String email= txtemail.getText();
        String contact= txtcno.getText();
        String type= cmbmtype.getSelectedItem().toString();
        
      
        try
        {
            String sql="UPDATE `addmember` SET `name`='"+name+"',`nic`='"+nic+"',`birthday`='"+birthday+"',`gender`='"+gender+"',`address`='"+address+"',`email`='"+email+"',`contact`='"+contact+"',`type`='"+type+"' WHERE `mid`='"+txtid.getText()+"' ";
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"update successful");
            table();
        }catch(Exception e)
        {
                        JOptionPane.showMessageDialog(rootPane,e);

        }
    }//GEN-LAST:event_btupdateActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel=(DefaultTableModel)tbldata.getModel();
        int selectrowindex =tbldata.getSelectedRow();
        
        
        
        txtid.setText(tmodel.getValueAt(selectrowindex,0).toString());
                txtname.setText(tmodel.getValueAt(selectrowindex,1).toString());
        txtnic.setText(tmodel.getValueAt(selectrowindex,2).toString());
        ((JTextField)calbday.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex,3).toString());

        
        
        
        
        
        cmbgender.setSelectedItem(tmodel.getValueAt(selectrowindex,4).toString());
         txtaddress.setText(tmodel.getValueAt(selectrowindex,5).toString());
          txtemail.setText(tmodel.getValueAt(selectrowindex,6).toString());
           txtcno.setText(tmodel.getValueAt(selectrowindex,7).toString());
                   cmbmtype.setSelectedItem(tmodel.getValueAt(selectrowindex,8).toString());
                   
                   
                   
                   
                   

           
        
        
        
    }//GEN-LAST:event_tbldataMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btupdate;
    private com.toedter.calendar.JDateChooser calbday;
    private javax.swing.JComboBox cmbgender;
    private javax.swing.JComboBox cmbmtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables
}
