/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class borrowhistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public borrowhistory() {
        initComponents();
        con=dbconnect.connect();
       // autoid();
       table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblborrowhistory = new javax.swing.JTable();
        todate = new com.toedter.calendar.JDateChooser();
        btfilter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 30)); // NOI18N
        jLabel15.setText("Borrow History");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 310, 60));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel16.setText("Member ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        txtsearch.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 40, 140, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 970, 100));

        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 180, 60));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 190, 60));

        tblborrowhistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblborrowhistory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 960, 400));

        todate.setDateFormatString("yyyy-MM-dd");
        todate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(todate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 120, 40));

        btfilter.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btfilter.setText("Filter");
        btfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfilterActionPerformed(evt);
            }
        });
        jPanel1.add(btfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel5.setText("To");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel4.setText("From");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        fromdate.setDateFormatString("yyyy-MM-dd");
        fromdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(fromdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 120, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setPreferredSize(new java.awt.Dimension(980, 600));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 960, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        try{
            
            String sql2="SELECT `recordno`, `mid`, `bid`, `idate`, `rdate` FROM `borrow` WHERE  mid LIKE '%"+txtsearch.getText()+"%'";
            pst= con.prepareStatement(sql2);
            rs=pst.executeQuery();
            tblborrowhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        txtsearch.setText("");
        table();
        ((JTextField)fromdate.getDateEditor().getUiComponent()).setText("");
        ((JTextField)todate.getDateEditor().getUiComponent()).setText("");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfilterActionPerformed
        try {
            // TODO add your handling code here:

            filter();
        } catch (SQLException ex) {
            Logger.getLogger(borrowhistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btfilterActionPerformed
    
    private void filter() throws SQLException
    {
        String fdate=((JTextField)fromdate.getDateEditor().getUiComponent()).getText().toString();
        String tdate=((JTextField)todate.getDateEditor().getUiComponent()).getText().toString();
        
        if(fdate.length()>0 && tdate.isEmpty())
        {
            try
            {
                String vname="SELECT `recordno`, `mid`, `bid`, `idate`, `rdate` FROM `borrow` WHERE idate ='"+fdate+"' AND mid LIKE '%"+txtsearch.getText()+"%'";
                
                pst=con.prepareStatement(vname);
                rs=pst.executeQuery();
                tblborrowhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"first date");
            }
        }
        else if( fdate.length()>0 && tdate.length()>0)
        {
            try
            {
                String vname="SELECT `recordno`, `mid`, `bid`, `idate`, `rdate` FROM `borrow` WHERE mid LIKE '%"+txtsearch.getText()+"%' AND idate BETWEEN '"+fdate+"' AND '"+tdate+"'";
                               pst=con.prepareStatement(vname);
                rs=pst.executeQuery();
                tblborrowhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }catch(Exception e)
            {
                 JOptionPane.showMessageDialog(rootPane,e);
            
        }
     
        
        
        
    }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"select date to filter date ");
        }
        
    }
    
    
    
    
    private void table()
    {
        try{
            
            String sql2="SELECT `recordno`, `mid`, `bid`, `idate`, `rdate` FROM `borrow` ";
            pst= con.prepareStatement(sql2);
            rs=pst.executeQuery();
            tblborrowhistory.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    /*private void autoid(){
        try
        {
            
            String sql1="SELECT `mid` FROM `addmember` ORDER BY mid DESC LIMIT 1";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                
                String rno= rs.getString("mid");
                int co= rno.length();
                String txt=rno.substring(0,2);
                String num=rno.substring(2,co);
                int n=Integer.parseInt(num);
                ++n;
                String sum=Integer.toString(n);
                String ftxt=txt+sum;
                txtid.setText(ftxt);
        }else
            {
                txtid.setText("MI1000");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }*/
    
    
  /*  private void clear()
    {
 String mid= txtid.getText();
        txtname.setText("");
        txtnic.setText("");
        ((JTextField)calbday.getDateEditor().getUiComponent()).setText("");
        cmbgender.setSelectedIndex(0);
                txtaddress.setText("");
        txtemail.setText("");
        txtcno.setText("");
        cmbmtype.setSelectedIndex(0);
        
        
        
        
        
        
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btfilter;
    private com.toedter.calendar.JDateChooser fromdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblborrowhistory;
    private com.toedter.calendar.JDateChooser todate;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
