/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class borrow extends javax.swing.JInternalFrame {

    /**
     * Creates new form borrow
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public borrow() {
        initComponents();
                con=dbconnect.connect();
        autoid();
        
        LocalDate today=LocalDate.now();
        LocalDate reday=today.plus(10,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtrdate.setText(reday.toString());
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtidate = new javax.swing.JTextField();
        txtrdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtrno = new javax.swing.JTextField();
        btclear = new javax.swing.JButton();
        btissue = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtbname = new javax.swing.JTextField();
        txtbtype = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtmtype = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblborrow = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel13.setText("Issue date");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel14.setText("Return date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        txtidate.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtidate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 320, 170, 40));

        txtrdate.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtrdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtrdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 320, 170, 40));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 710, 100));

        txtrno.setEditable(false);
        txtrno.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtrno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 170, 50));

        btclear.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        btclear.setText("Clear");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        jPanel1.add(btclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 163, 170, 50));

        btissue.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        btissue.setText("Issue");
        btissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btissueActionPerformed(evt);
            }
        });
        jPanel1.add(btissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 273, 170, 50));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 210, 370));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel10.setText("Book Id");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel11.setText("Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel12.setText("Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        txtbookid.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtbookid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbookidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 130, 30));

        txtbname.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtbname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 130, 30));

        txtbtype.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtbtype.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtypeActionPerformed(evt);
            }
        });
        jPanel1.add(txtbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 130, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 370, 260));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel7.setText("Member Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel9.setText("Member type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        txtmid.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtmid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmidActionPerformed(evt);
            }
        });
        txtmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmidKeyReleased(evt);
            }
        });
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, 30));

        txtmname.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 130, 30));

        txtmtype.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        txtmtype.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 260));

        tblborrow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tblborrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblborrow);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 400, 930, 150));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 550));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void autoid(){
        try
        {
            
            String sql1="SELECT `recordno` FROM `borrow` ORDER BY recordno DESC LIMIT 1";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                
                String rno= rs.getString("recordno");
                int co= rno.length();
                String txt=rno.substring(0,2);
                String num=rno.substring(2,co);
                int n=Integer.parseInt(num);
                ++n;
                String sum=Integer.toString(n);
                String ftxt=txt+sum;
                txtrno.setText(ftxt);
        }else
            {
                txtrno.setText("RN1000");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbtypeActionPerformed

    private void txtmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmidActionPerformed

    private void txtmidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmidKeyReleased
        // TODO add your handling code here:
        
            try{
        
            
            String sql1="SELECT  `name`,`type` FROM `addmember` WHERE mid='"+txtmid.getText()+"'";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                txtmname.setText(rs.getString("name"));
                txtmtype.setText(rs.getString("type"));
              
        }
            }catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
    
    }//GEN-LAST:event_txtmidKeyReleased

    private void txtbookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookidKeyReleased
        // TODO add your handling code here:
                try{
        
            
            String sql1="SELECT `bname`,`booktype` FROM `addbook` WHERE bid='"+txtbookid.getText()+"'";
            //SELECT `mid` FROM `addmember`
            
            pst=con.prepareStatement(sql1);
            
            rs=pst.executeQuery();
            
            
            if(rs.next())
            {
                txtbname.setText(rs.getString("bname"));
                txtbtype.setText(rs.getString("booktype"));
              
        }
            else
            {
                txtbname.setText("");
                                txtbname.setText("");

            }
            }catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
    
    
        
        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_txtbookidKeyReleased
private void table()
    {
        try{
            
            String sql2="SELECT `recordno`, `mid`, `bid`, `idate`, `rdate` FROM `borrow` ";
            pst= con.prepareStatement(sql2);
            rs=pst.executeQuery();
            tblborrow.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

private void clear()
{
    txtmid.setText("");
    txtbookid.setText("");
    txtmname.setText("");
    txtmtype.setText("");
    txtbname.setText("");
    txtbtype.setText("");
    
    
}
private void update()
{
    try
    {
        String sql="UPDATE `addbook` SET `mark`='1' WHERE bid='"+txtbookid.getText()+"' ";
         pst=con.prepareStatement(sql);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane,"update successful");
           // table();
            
            
 
        
        
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
        
    
   // update();
    
}
    

    
    
    
    
    private void btissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btissueActionPerformed
        // TODO add your handling code here:
        
        String rno=txtrno.getText();
         String mid=txtmid.getText();
        String bid=txtbookid.getText();
        String idate=txtidate.getText();
        String rdate=txtrdate.getText();
       
        
           try
        {
            
            String sql="INSERT INTO `borrow`(`recordno`, `mid`, `bid`, `idate`, `rdate`,mark) VALUES('"+rno+"','"+mid+"','"+bid+"','"+idate+"','"+rdate+"','0')";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.executeUpdate();                          
                         JOptionPane.showMessageDialog(rootPane,"successful entered");
          
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
           
           update();
           table();
           clear();
           autoid();
     
    }//GEN-LAST:event_btissueActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        // TODO add your handling code here:
      clear();
    }//GEN-LAST:event_btclearActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclear;
    private javax.swing.JButton btissue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblborrow;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbtype;
    private javax.swing.JTextField txtidate;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmtype;
    private javax.swing.JTextField txtrdate;
    private javax.swing.JTextField txtrno;
    // End of variables declaration//GEN-END:variables
}

