/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
//import java.util.Timer;

/**
 *
 * @author dell
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     * 
     */
    Connection con= null;
    public Home() {
        initComponents();
        clock();
         con=dbconnect.connect(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void clock()
    {
        Thread clock = new Thread()
        {
            public void run()
            {
                try{
                    while(true)
                    {
                        Calendar cal = new GregorianCalendar();
                        int day= cal.get(Calendar.DAY_OF_MONTH);
                        int month =cal.get(Calendar.MONTH);
                        int year= cal.get(Calendar.YEAR);
                        
                        int second= cal.get(Calendar.SECOND);
                        int minute= cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        
                        lbdate.setText(hour+":"+minute+":"+second);
                        lbtime.setText(day+":"+month+":"+year);
                        
                        sleep(1000);
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,e);
                    //JOptionpane.showMessegeDialog()
                }
            }
        };
        clock.start();
    }
                       
            
                       
                    
                
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btallbooks = new javax.swing.JButton();
        btallmembers = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        homedtop = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        btborrow = new javax.swing.JButton();
        btreturn = new javax.swing.JButton();
        btaddmember = new javax.swing.JButton();
        btaddbook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btallbooks.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btallbooks.setText("All Books");
        btallbooks.setFocusable(false);
        btallbooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btallbooks.setMargin(new java.awt.Insets(2, 50, 2, 50));
        btallbooks.setMaximumSize(new java.awt.Dimension(145, 25));
        btallbooks.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btallbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btallbooksActionPerformed(evt);
            }
        });
        jToolBar1.add(btallbooks);

        btallmembers.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btallmembers.setText("All Members");
        btallmembers.setFocusable(false);
        btallmembers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btallmembers.setMargin(new java.awt.Insets(2, 50, 2, 50));
        btallmembers.setMaximumSize(new java.awt.Dimension(145, 25));
        btallmembers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btallmembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btallmembersActionPerformed(evt);
            }
        });
        jToolBar1.add(btallmembers);

        jButton3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton3.setText("Borrow history");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(2, 50, 2, 50));
        jButton3.setMaximumSize(new java.awt.Dimension(145, 25));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton4.setText("Pending List");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(2, 50, 2, 50));
        jButton4.setMaximumSize(new java.awt.Dimension(145, 25));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton5.setText("Log Out");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMargin(new java.awt.Insets(2, 50, 2, 50));
        jButton5.setMaximumSize(new java.awt.Dimension(145, 25));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));
        jPanel1.add(homedtop, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 980, 600));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 28)); // NOI18N
        jLabel4.setText("My Library");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        lbdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(lbdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 160, -1));

        lbtime.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel1.add(lbtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 160, -1));

        btborrow.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btborrow.setText("Borrow");
        btborrow.setFocusable(false);
        btborrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btborrow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btborrowActionPerformed(evt);
            }
        });
        jPanel1.add(btborrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));

        btreturn.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btreturn.setText("return");
        btreturn.setFocusable(false);
        btreturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btreturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, -1));

        btaddmember.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btaddmember.setText("Add member");
        btaddmember.setFocusable(false);
        btaddmember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btaddmember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btaddmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddmemberActionPerformed(evt);
            }
        });
        jPanel1.add(btaddmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 450, 170, -1));

        btaddbook.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btaddbook.setText("Add book");
        btaddbook.setFocusable(false);
        btaddbook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btaddbook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddbookActionPerformed(evt);
            }
        });
        jPanel1.add(btaddbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 590, 170, -1));

        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 110, -1));

        jButton2.setText("new home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 600));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel5.setText("Time:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 60));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddbookActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        addbook adb= new addbook();
        homedtop.add(adb).setVisible(true);
    }//GEN-LAST:event_btaddbookActionPerformed

    private void btaddmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddmemberActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        Addmember ad= new Addmember();
        homedtop.add(ad).setVisible(true);
        
    }//GEN-LAST:event_btaddmemberActionPerformed

    private void btreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreturnActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        returns re= new returns();
        homedtop.add(re).setVisible(true);
        
        
    }//GEN-LAST:event_btreturnActionPerformed

    private void btborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrowActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        borrow bo= new borrow();
        homedtop.add(bo).setVisible(true);
        
    }//GEN-LAST:event_btborrowActionPerformed

    private void btallbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btallbooksActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        Allbooks ad= new Allbooks();
        homedtop.add(ad).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btallbooksActionPerformed

    private void btallmembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btallmembersActionPerformed
        // TODO add your handling code here:
homedtop.removeAll();
        Allmember ad= new Allmember();
        homedtop.add(ad).setVisible(true);
        
    }//GEN-LAST:event_btallmembersActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         homedtop.removeAll();
        pendinglist ad= new pendinglist();
        homedtop.add(ad).setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        homedtop.removeAll();
        borrowhistory ad= new borrowhistory();
        homedtop.add(ad).setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home he= new Home();
        he.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddbook;
    private javax.swing.JButton btaddmember;
    private javax.swing.JButton btallbooks;
    private javax.swing.JButton btallmembers;
    private javax.swing.JButton btborrow;
    private javax.swing.JButton btreturn;
    private javax.swing.JDesktopPane homedtop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbtime;
    // End of variables declaration//GEN-END:variables
}
