/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class returns extends javax.swing.JInternalFrame {

    /**
     * Creates new form returns
     */
     Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public returns() {
        initComponents();
             con=dbconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtbookid = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        txtldays = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(980, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 340, 40));

        txtbookid.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        txtbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbookidKeyReleased(evt);
            }
        });
        jPanel2.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, 30));

        txtmid.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        txtmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmidActionPerformed(evt);
            }
        });
        jPanel2.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 200, 180, 30));

        txtldays.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        txtldays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtldaysActionPerformed(evt);
            }
        });
        jPanel2.add(txtldays, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, 30));

        txtfine.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });
        jPanel2.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 180, 30));

        txtbill.setColumns(20);
        txtbill.setRows(5);
        txtbill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtbill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 90, 300, 340));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel5.setText("Book ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 114, 110, 30));

        jButton2.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 450, 240, 40));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel6.setText("Member ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 40));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel7.setText("Late Days");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 50));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel8.setText("Fine");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 350));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 80));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 550));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmidActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

    private void txtldaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtldaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtldaysActionPerformed

    private void txtbookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookidKeyReleased
        // TODO add your handling code here:
        
        try
        {
            
            String sql= "SELECT  `mid`, `rdate` FROM `borrow`  where bid='"+txtbookid.getText()+"' and mark='0'";
                       pst= con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                txtmid.setText(rs.getString("mid"));
                String rdate=rs.getString("rdate");
                
                LocalDate today = LocalDate.now();
                
                LocalDate rday=LocalDate.parse(rdate);
                
                Long day_gap=ChronoUnit.DAYS.between(rday,today);
                if(day_gap>0)
                {   
                txtldays.setText(day_gap.toString());
                
                
                long fine=10*day_gap;
                txtfine.setText(String.valueOf(fine));
                }
                else
                {
                    txtfine.setText("0");
                    txtldays.setText("0");
                    
                    
                    
                }
                
                
                
                
            }
           
            
            
        }catch(Exception e)
        {
            
        }
        
        
        
        
    }//GEN-LAST:event_txtbookidKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String bid=txtbookid.getText();
        
                String mid=txtmid.getText();
                        String late_day= txtldays.getText();
                                String fine=txtfine.getText();
        
            try
        {
            
            String sql="INSERT INTO `bookreturn`(`bid`, `mid`, `late_day`, `fine`) VALUES('"+bid+"','"+mid+"','"+late_day+"','"+fine+"')";
        PreparedStatement pst1= con.prepareStatement(sql);
        pst1.executeUpdate();   
        update();
        bill();
        returnmark();
        
                         JOptionPane.showMessageDialog(rootPane,"successful insert");
          
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
     
      
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
             // TODO add your handling code here:

             txtbill.print();
         } catch (PrinterException ex) {
             Logger.getLogger(returns.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bill()
    {
     
        txtbill.setText("==================================="+"\n"+"My Library"+"\n"+"No of date\t"+txtldays.getText()+"\n"+"Amount\t"+txtfine.getText()+"\n"+"===================================");
        
    }
    
    
    
    
    private void update()
{
    try
    {
        String sql="UPDATE `addbook` SET `mark`='0' WHERE bid='"+txtbookid.getText()+"' ";
         pst=con.prepareStatement(sql);
            
            pst.executeUpdate();
            
         //   JOptionPane.showMessageDialog(rootPane,"update successful");
           // table();
            
            
 
        
        
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
        
    
   // update();
    
}
    
        private void returnmark()
{
    try
    {
        String sql="UPDATE `borrow` SET `mark`='1' WHERE bid='"+txtbookid.getText()+"' ";
         pst=con.prepareStatement(sql);
            
            pst.executeUpdate();
            
         //   JOptionPane.showMessageDialog(rootPane,"update successful");
           // table();
            
            
 
        
        
        
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
        
    
   // update();
    
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtldays;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables
}
